name: docdoc_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.3+1

environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  #network image 
  cached_network_image:
  #A build system for Dart code generation and modular compilation
  build_runner:

  #state management 
  flutter_bloc: ^9.1.1
  #code generator(mainly used with cubit & retrofit)
  freezed: ^3.2.3
  freezed_annotation: ^3.1.0
  #Dependency injection
  get_it: ^8.2.0
  # Automatically generate code for converting to and from JSON by annotating Dart classes
  json_annotation: ^4.9.0
  json_serializable: ^6.11.1
  # Networking
  dio: ^5.9.0
  retrofit:
  retrofit_generator:
  pretty_dio_logger:

  # localization
  intl: ^0.20.2
  easy_localization: ^3.0.8
  #for splash screen
  flutter_native_splash: ^2.4.6
  # for adapting screen and font size.
  flutter_screenutil: ^5.9.3

  #An SVG rendering and widget library for Flutter, which allows painting 
  flutter_svg: ^2.2.1

  #Firebase 
  firebase_core:

  # reading and writing simple key-value pairs
  shared_preferences: ^2.5.3

  # provides API to store data in secure storage.
  flutter_secure_storage: ^9.2.4

  # easy way to add shimmer effect
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
  - assets/images/
  - assets/svgs/
