name: docdoc_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  #state management 
  flutter_bloc: ^9.1.1
  #code generator(mainly used with cubit & retrofit)
  freezed: ^3.2.3
  freezed_annotation: ^3.1.0
  #Dependency injection
  get_it: ^8.2.0
  # Automatically generate code for converting to and from JSON by annotating Dart classes
  json_annotation: ^4.9.0
  json_serializable: ^6.11.1
  # Networking
  dio: ^5.9.0
  retrofit: ^4.7.3
  retrofit_generator: ^10.0.6
  pretty_dio_logger: ^1.4.0
  # localization
  intl: ^0.20.2
  easy_localization: ^3.0.8
  #for splash scree,
  flutter_native_splash: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
